import Head from "next/head";
import { AllBackground } from "../components/AllBackground";
import { Footer } from "../components/Footer";
import { GetAccess } from "../components/GetAccess";
import { Productive } from "../components/Productive";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
        <title>Home | Frontend Mentor</title>
      </Head>

      <AllBackground />
      <Productive />
      <GetAccess />
      <Footer />
    </div>
  );
}
