import Head from 'next/head'
import { AllBackground } from '../components/AllBackground'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <AllBackground />
    </div>
  )
}
