import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <h1>Hello World Fylo</h1>
    </div>
  )
}
